[package]
name = "png-display"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
bitreader = "0.3.8"
color-print = "0.3.6"
crc32fast = "1.4.2"
inflate = "0.4.5"
minifb = "0.27.0"
nom = "7.1.3"
seq-macro = "0.3.5"
